# avoid duplicate builds
if: tag IS NOT present

# safelist
branches:
  only:
    - master

# context
language: node_js
node_js:
  - '8'

# setup
install: yarn
script: yarn deploy
cache:
  directories:
    - "node_modules"
